### ISSUE TITLE
Pie chart broken

### ISSUE THREAD

**Issue by wendt88** [nativescript-community/ui-chart#29]
**Summary**
Error occurs on `PieChart` (on `setData`)

**Error**
```
System.err: An uncaught Exception occurred on "main" thread.
System.err: Calling js method onDraw failed
System.err: TypeError: Cannot read property 'setColor' of undefined
System.err:
System.err: StackTrace:
System.err: drawValues(file: app\src\renderer\PieChartRenderer.ts:459:33)
System.err:     at onDraw(file: app\src\charts\PieChart.ts:130:23)
System.err:     at onDraw(file: app\src\canvas.android.ts:618:21)
System.err:     at com.tns.Runtime.callJSMethodNative(Native Method)
System.err:     at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1302)
System.err:     at com.tns.Runtime.callJSMethodImpl(Runtime.java:1188)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1175)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1153)
System.err:     at com.tns.Runtime.callJSMethod(Runtime.java:1149)
System.err:     at com.tns.gen.com.akylas.canvas.DrawListener.onDraw(DrawListener.java:18)
System.err:     at com.akylas.canvas.CanvasView.onDraw(CanvasView.java:27)
System.err:     at android.view.View.draw(View.java:22350)
System.err:     at android.view.View.updateDisplayListIfDirty(View.java:21226)
System.err:     at android.view.View.draw(View.java:22081)
System.err:     at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
System.err:     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
System.err:     at android.view.View.updateDisplayListIfDirty(View.java:21217)
System.err:     at android.view.View.draw(View.java:22081)
System.err:     at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
System.err:     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
System.err:     at android.view.View.updateDisplayListIfDirty(View.java:21217)
System.err:     at android.view.View.draw(View.java:22081)
System.err:     at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
System.err:     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
System.err:     at android.view.View.updateDisplayListIfDirty(View.java:21217)
System.err:     at android.view.View.draw(View.java:22081)
System.err:     at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
System.err:     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
System.err:     at android.view.View.updateDisplayListIfDirty(View.java:21217)
System.err:     at android.view.View.draw(View.java:22081)
System.err:     at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
System.err:     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
System.err:     at android.view.View.updateDisplayListIfDirty(View.java:21217)
System.err:     at android.view.View.draw(View.java:22081)
System.err:     at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
System.err:     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
System.err:     at android.view.View.draw(View.java:22353)
System.err:     at android.view.View.updateDisplayListIfDirty(View.java:21226)
System.err:     at android.view.View.draw(View.java:22081)
System.err:     at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
System.err:     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
System.err:     at android.view.View.draw(View.java:22353)
System.err:     at android.view.View.updateDisplayListIfDirty(View.java:21226)
System.err:     at android.view.View.draw(View.java:22081)
System.err:     at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
System.err:     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
System.err:     at android.view.View.updateDisplayListIfDirty(View.java:21217)
System.err:     at android.view.View.draw(View.java:22081)
System.err:     at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
System.err:     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
System.err:     at android.view.View.updateDisplayListIfDirty(View.java:21217)
System.err:     at android.view.View.draw(View.java:22081)
System.err:     at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
System.err:     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
System.err:     at android.view.View.draw(View.java:22353)
System.err:     at android.view.View.updateDisplayListIfDirty(View.java:21226)
System.err:     at android.view.View.draw(View.java:22081)
System.err:     at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
System.err:     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
System.err:     at android.view.View.draw(View.java:22353)
System.err:     at android.view.View.updateDisplayListIfDirty(View.java:21226)
System.err:     at android.view.View.draw(View.java:22081)
System.err:     at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
System.err:     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
System.err:     at android.view.View.updateDisplayListIfDirty(View.java:21217)
System.err:     at android.view.View.draw(View.java:22081)
System.err:     at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
System.err:     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
System.err:     at android.view.View.updateDisplayListIfDirty(View.java:21217)
System.err:     at android.view.View.draw(View.java:22081)
System.err:     at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
System.err:     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
System.err:     at android.view.View.updateDisplayListIfDirty(View.java:21217)
System.err:     at android.view.View.draw(View.java:22081)
System.err:     at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
System.err:     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
System.err:     at android.view.View.updateDisplayListIfDirty(View.java:21217)
System.err:     at android.view.View.draw(View.java:22081)
System.err:     at android.view.ViewGroup.drawChild(ViewGroup.java:4516)
System.err:     at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4277)
System.err:     at android.view.View.draw(View.java:22353)
System.err:     at com.android.internal.policy.DecorView.draw(DecorView.java:806)
System.err:     at android.view.View.updateDisplayListIfDirty(View.java:21226)
System.err:     at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:559)
System.err:     at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:565)
System.err:     at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:642)
System.err:     at android.view.ViewRootImpl.draw(ViewRootImpl.java:4101)
System.err:     at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3828)
System.err:     at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3099)
System.err:     at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1952)
System.err:     at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8171)
System.err:     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:972)
System.err:     at android.view.Choreographer.doCallbacks(Choreographer.java:796)
System.err:     at android.view.Choreographer.doFrame(Choreographer.java:731)
System.err:     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:957)
System.err:     at android.os.Handler.handleCallback(Handler.java:938)
System.err:     at android.os.Handler.dispatchMessage(Handler.java:99)
System.err:     at android.os.Looper.loop(Looper.java:223)
System.err:     at android.app.ActivityThread.main(ActivityThread.java:7656)
System.err:     at java.lang.reflect.Method.invoke(Native Method)
System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
System.err: com.tns.NativeScriptException: TypeError: Cannot read property 'FirebaseCrashlytics' of undefined
System.err:     at com.tns.Runtime.passExceptionToJsNative(Native Method)
System.err:     at com.tns.Runtime.passUncaughtExceptionToJs(Runtime.java:84)
System.err:     at com.tns.NativeScriptUncaughtExceptionHandler.uncaughtException(NativeScriptUncaughtExceptionHandler.java:34)
System.err:     at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1073)
System.err:     at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
System.err:     at java.lang.Thread.dispatchUncaughtException(Thread.java:2203)
```

**Device (please complete the following information):**
 - Device: Google Pixel 4
 - Android Version: 11
 - Library Version: 1.1.32

**Additional Context**
tried the [pie chart example](https://github.com/nativescript-community/ui-chart/blob/master/demo/app/examples/PieChart.ts) from demo folder and it does not work

**Comment by farfromrefug** [comment]
@wendt88 should be fixed in 1.1.33

**Comment by wendt88** [comment]
great!
tested and seems ok
